### ISSUE TITLE
cannot find package “.../v4”

### ISSUE THREAD

**Issue by iReadX** [thecodingmachine/gotenberg-go-client#2]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Steps to Reproduce (for bugs)

1.go get -u github.com/thecodingmachine/gotenberg-go-client/v4
2.cannot find package "github.com/thecodingmachine/gotenberg-go-client/v4"
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by gulien** [comment]
Which version of Go are you using?
