### ISSUE TITLE
go get github.com/thecodingmachine/gotenberg-go-client: no matching versions for query "upgrade"

### ISSUE THREAD

**Issue by anushareguri-spec** [thecodingmachine/gotenberg-go-client#29]
go version go1.16.3 linux/amd64

Unable to pull github.com/thecodingmachine/gotenberg-go-client when GO111MODULE=on
getting below error when i run "go get github.com/thecodingmachine/gotenberg-go-client" 
go get github.com/thecodingmachine/gotenberg-go-client: no matching versions for query "upgrade"

**Comment by ru4sam326** [comment]
Any update on this please?
