### ISSUE TITLE
 dial tcp [::1]:3000: connect: connection refused

### ISSUE THREAD

**Issue by alibaltschun** [thecodingmachine/gotenberg-go-client#5]
## Expected Behavior
create a pdf file

## Current Behavior
panic: store error : Post http://localhost:3000/convert/office: dial tcp [::1]:3000: connect: connection refused

## Steps to Reproduce (for bugs)
```
package main

import gotenberg "github.com/thecodingmachine/gotenberg-go-client"

func main() {
	c := &gotenberg.Client{Hostname: "http://localhost:3000"}
	req, err := gotenberg.NewOfficeRequest("/home/koni/test_gotenberg/test.docx")
	if err != nil {
		panic("office request error : " + err.Error())
	}

	dest := "/home/koni/test_gotenberg/test.pdf"
	err = c.Store(req, dest)
	if err != nil {
		panic("store error : " + err.Error())
	}
}
```

## Your Environment
* Version used: 
* Operating System and version: manjaro kernel 4.19
* Link to your project:

**Comment by gulien** [comment]
Hello @alibaltschun 

Did you start the API with `docker run --rm -p 3000:3000 thecodingmachine/gotenberg:5` ?

Also please note the import path should be `import "github.com/thecodingmachine/gotenberg-go-client/v5"` :)

**Comment by alibaltschun** [comment]
i tried `go get -u github.com/thecodingmachine/gotenberg-go-client/v5` but give me an error, so i remove the v5 while go get.

and the server was up
```
docker-compose up --scale gotenberg=1
Attaching to test_gotenberg_gotenberg_1
gotenberg_1  | ⇨ Gotenberg 5.0.0
gotenberg_1  | ⇨ starting Google Chrome headless with PM2...
gotenberg_1  | ⇨ starting unoconv listener with PM2...
gotenberg_1  | ⇨ http server started on port 3000



```

**Comment by gulien** [comment]
@alibaltschun thank you for the feedback!

In your `docker-compose.yml`, did you map your host port `3000` with the the Gotenberg container port `3000`?

What kind of error do you get by running `go get -u github.com/thecodingmachine/gotenberg-go-client/v5`? Also, are you using go modules?

**Comment by alibaltschun** [comment]
thanks , the problem coz I did not map the port
